name: package-js-release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0

      - name: Setup Node 12.x
        uses: actions/setup-node@v1

      - uses: actions/setup-go@v1
        with:
          version: 1.13

      - name: Authenticate docker
        run: |
          echo "${{ secrets.GCLOUD_AUTH }}" | base64 -d | docker login -u _json_key --password-stdin https://eu.gcr.io

      - name: Build
        run: |
          make publish-release
        env:
          IMAGE_NAMESPACE: eu.gcr.io/segmentstream
